### ISSUE TITLE
Error: install error: package '@svrx/svrx' not found: must call as: npm.load(callback)

### ISSUE THREAD

**Issue by QasimArif** [brycewray/eleventy_solo_starter#1] opened 2020-12-11 03:00 UTC
Hey @brycewray,

Once I get to NPM run start, I'm facing the below error. I've run NPM install beforehand for all the dependancies and have tried this "npm install -g @svrx/cli"& "npm install --save-dev @svrx/svrx" but with no luck. Any idea what's going on?

`> eleventy_solo@1.0.0 start
> npm-run-all clean imgs --parallel dev:*

> eleventy_solo@1.0.0 clean
> rm -rf _site

> eleventy_solo@1.0.0 imgs
> node imgxfm.js

Writing responsive images...

> eleventy_solo@1.0.0 dev:svrx
> svrx

> eleventy_solo@1.0.0 dev:postcss
> postcss src/assets/css/index.css -d _site/css/ --config ./postcss.config.js -w

> eleventy_solo@1.0.0 dev:eleventy
> ELEVENTY_ENV=development npx @11ty/eleventy --watch --quiet

[error] Error: install error: package '@svrx/svrx' not found: must call as: npm.load(callback)
npm ERR! code 1
npm ERR! path /Users/XXX/Documents/GitHub/eleventy_solo_starter
npm ERR! command failed
npm ERR! command sh -c svrx

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXX/.npm/_logs/2020-12-11T02_54_05_729Z-debug.log
ERROR: "dev:svrx" exited with 1.
npm ERR! code 1
npm ERR! path /Users/XXX/Documents/GitHub/eleventy_solo_starter
npm ERR! command failed
npm ERR! command sh -c npm-run-all clean imgs --parallel dev:*

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXX/.npm/_logs/2020-12-11T02_54_06_590Z-debug.log`

**Comment by brycewray** [comment] 2020-12-11 08:30
@QasimArif Unable to reproduce the error here, so — based on your statement that you've done a full `npm install` — I honestly don’t know what could be causing this. **Note**: Be advised I’m currently revising this starter repo for other reasons (mainly, fixing CSS hashing), so perhaps you might want to wait a few hours and grab it again. I have no idea whether it will have any effect on the problem you’re seeing with `svrx`, but at least you’ll have what then will be an updated version. Sorry I can’t be more helpful. (For the record, my local environment is macOS Big Sur on an Intel-based Mac; no idea whether that is relevant to your issue.)

**Comment by QasimArif** [comment] 2020-12-11 09:16
@brycewray thanks for the prompt reply! I’ve got a way around it by running the build command and serve command (npx eleventy --serve). Looks to have done the job!

And thanks for letting me know, I’ll keep an eye out in a few hours for the latest version.

**Comment by brycewray** [comment] 2020-12-11 09:28
@QasimArif good to know that you got it going, although I'm still at a loss as to the cause of the problem.

(BTW, my sort-of-quick response is due to insomnia. Where I am, it’s **very** early. 😄 )

And, actually, the latest is up now. Note that it has a number of package updates in addition to the main fix I was incorporating. Hope it works well for you, with or without the fix you found.

**Comment by TedisAgolli** [comment] 2021-01-03 02:31
I just got the same error. Happened on Ubuntu 20.04 if that helps at all.
I tried removing "--parallel" from the "start" command in package.json, and the "imgs"  command no longer fails but hangs forever.
Everything works fine if I run "node run imgs". The offender definitely looks to be imgxfm.js though.

The fix by @QasimArif worked.

**Comment by brycewray** [comment] 2021-01-03 14:40
> I just got the same error. Happened on Ubuntu 20.04 if that helps at all.
> 
> I tried removing "--parallel" from the "start" command in package.json, and the "imgs"  command no longer fails but hangs forever.
> 
> Everything works fine if I run "node run imgs". The offender definitely looks to be imgxfm.js though.
> 
> 
> 
> The fix by @QasimArif worked. 

@TedisAgolli I'll look into it. Thanks for the additional info.

**Comment by brycewray** [comment] 2021-01-03 14:51
@TedisAgolli - out of curiosity, what version of Node are you running?

**Comment by brycewray** [comment] 2021-01-03 14:54
@QasimArif and @TedisAgolli I now see this in the `svrx` repo issues: https://github.com/svrxjs/svrx/issues/191 — so I may need to rethink using `svrx` for now.

**Comment by brycewray** [comment] 2021-01-03 15:00
Reopening this until I figure out a way around https://github.com/svrxjs/svrx/issues/191 — and this will obviously affect my other repos using `svrx` (e.g., https://github.com/brycewray/eleventy_solo_starter_njk and https://github.com/brycewray/eleventy_solo).

**UPDATE**: Have just reverted all my affected repos to using `browser-sync` (its latest update, despite what its **Releases** info says on its GitHub front page, is from just a few months ago and seems to have addressed some notable problems). Would advise @QasimArif and @TedisAgolli, as well as any others experiencing similar problems noted in this issue, to try this repo this way and see if that eliminates the needs for the workarounds described.

**Comment by TedisAgolli** [comment] 2021-01-03 18:48
Works fine now! Thanks.

**Comment by brycewray** [comment] 2021-01-03 18:49
> Works fine now! Thanks.

@TedisAgolli that's great! Think we're good to close this one again?

**Closed as completed** 2021-01-14 16:52 UTC
